Repository mental-jober/backend, pull requests merged in 2023-09, with the labels that each got.

#31 개발환경/운영환경 분리 (application.yml)
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: enhancement

#32 임시저장 관련 로직 설계
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallTempController.java
  src/main/java/com/fastcampus/jober/domain/spacewall/domain/SpaceWallTemp.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallTempDTO.java
  src/main/java/com/fastcampus/jober/domain/spacewall/repository/SpaceWallTempRepo.java
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallTempService.java
Labels: enhancement

#36 임시저장 초기 로직 구현
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallTempController.java
  src/main/java/com/fastcampus/jober/domain/spacewall/domain/SpaceWallTemp.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallTempDTO.java
  src/main/java/com/fastcampus/jober/domain/spacewall/repository/SpaceWallTempRepository.java
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallTempService.java
Labels: enhancement

#43 MyTemplate 엔티티 templates 필드 단일구조로 변경
  src/main/java/com/fastcampus/jober/domain/template/domain/MyTemplate.java
  src/main/java/com/fastcampus/jober/domain/template/repository/MyTemplateRepository.java
  src/main/java/com/fastcampus/jober/domain/template/service/MyTemplateService.java
Labels: refactor

#52 동시 편집 접근 제한 기능 구현
  build.gradle
  src/main/java/com/fastcampus/jober/JoberApplication.java
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallController.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallResponse.java
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallService.java
  src/main/java/com/fastcampus/jober/global/config/RedisConfig.java
Labels: enhancement

#53 ApiUtil 클래스 제거
  src/main/java/com/fastcampus/jober/global/util/ApiUtil.java
Labels: enhancement

#54 템플릿 관련 API 공통 응답 바디 클래스 수정
  src/main/java/com/fastcampus/jober/domain/template/controller/MyTemplateController.java
  src/main/java/com/fastcampus/jober/domain/template/controller/TemplateController.java
  src/main/java/com/fastcampus/jober/global/error/advice/MyExceptionAdvice.java
Labels: refactor

#57 application-prod.yml redis 환경 추가
  src/main/resources/application-prod.yml
Labels: enhancement

#59 히스토리 관련 Entity, DTO 생성 및 수정
  src/main/java/com/fastcampus/jober/domain/componenthistory/domain/ComponentHistory.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/dto/ComponentHistoryRequest.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/dto/ComponentHistoryResponse.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/domain/SpaceWallHistory.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/dto/SpaceWallHistoryRequest.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/dto/SpaceWallHistoryResponse.java
  src/main/java/com/fastcampus/jober/global/constant/Type.java
Labels: enhancement

#60 RedisConfig 오류 수정
  src/main/java/com/fastcampus/jober/global/config/RedisConfig.java
Labels: bug

#65 권한 설정 오류 수정 및 히스토리 저장 API 추가
  src/main/java/com/fastcampus/jober/domain/componenthistory/domain/ComponentHistory.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/dto/ComponentHistoryRequest.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/dto/ComponentHistoryResponse.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/repository/ComponentHistoryRepository.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/service/ComponentHistoryService.java
  src/main/java/com/fastcampus/jober/domain/member/controller/MemberController.java
  src/main/java/com/fastcampus/jober/domain/member/dto/MemberResponse.java
  src/main/java/com/fastcampus/jober/domain/member/service/MemberService.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/controller/SpaceWallHistoryController.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/domain/SpaceWallHistory.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/dto/HistoryWrapper.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/dto/SpaceWallHistoryRequest.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/dto/SpaceWallHistoryResponse.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/repository/SpaceWallHistoryRepository.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/service/SpaceWallHistoryService.java
  src/main/java/com/fastcampus/jober/domain/spacewallmember/controller/SpaceWallMemberController.java
  src/main/java/com/fastcampus/jober/domain/template/service/MyTemplateService.java
  src/main/java/com/fastcampus/jober/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/fastcampus/jober/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/fastcampus/jober/global/config/CustomLogoutHandler.java
  src/main/java/com/fastcampus/jober/global/config/JsonLogoutSuccessHandler.java
  src/main/java/com/fastcampus/jober/global/config/SecurityConfig.java
  src/main/java/com/fastcampus/jober/global/constant/ErrorCode.java
  src/main/java/com/fastcampus/jober/global/error/advice/MyExceptionAdvice.java
  src/main/java/com/fastcampus/jober/global/utils/FilterResponseUtils.java
Labels: refactor

#67 동시편집 체크 API URL 변경
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallController.java
Labels: refactor

#68 히스토리 조회 및 불러오기 api 개발
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/controller/SpaceWallHistoryController.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/repository/SpaceWallHistoryRepository.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/service/SpaceWallHistoryService.java
Labels: enhancement

#69 더미데이터 오류 수정
  src/main/resources/db/data-mysql.sql
Labels: refactor

#76 공유스페이스 URL 수정 API 구현
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallController.java
  src/main/java/com/fastcampus/jober/domain/spacewall/domain/SpaceWall.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallRequest.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallResponse.java
  src/main/java/com/fastcampus/jober/domain/spacewall/repository/SpaceWallRepository.java
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallService.java
Labels: enhancement

#78 공유스페이스 조회 API 컴퍼넌트 추가
  src/main/java/com/fastcampus/jober/domain/component/repository/ComponentRepository.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallResponse.java
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallService.java
  src/main/resources/db/data-h2.sql
  src/main/resources/db/data-mysql.sql
Labels: enhancement

#80 히스토리 createMemberId 수정
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/service/SpaceWallHistoryService.java
  src/main/java/com/fastcampus/jober/global/auth/session/MemberDetails.java
  src/main/resources/db/data-mysql.sql
Labels: refactor

#81 공유스페이스 생성 버그
  src/main/java/com/fastcampus/jober/domain/spacewallmember/domain/SpaceWallMember.java
  src/main/java/com/fastcampus/jober/domain/spacewallmember/repository/SpaceWallMemberRepository.java
  src/main/java/com/fastcampus/jober/domain/spacewallpermission/service/SpaceWallPermissionService.java
Labels: bug
