Repository mental-jober/backend, pull requests merged in 2023-10, with the labels that each got.

#88 공유스페이스에서 빈 공유스페이스 api 구현
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallCreationController.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallRequest.java
  src/main/java/com/fastcampus/jober/domain/spacewall/dto/SpaceWallResponse.java
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallService.java
Labels: enhancement

#90 공유스페이스 전체공개 / 비공개 API 구현
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallController.java
  src/main/java/com/fastcampus/jober/domain/spacewall/domain/SpaceWall.java
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallService.java
Labels: enhancement

#92 공동작업자 추가 API 오류 수정
  src/main/java/com/fastcampus/jober/domain/member/controller/MemberController.java
  src/main/java/com/fastcampus/jober/domain/member/service/MemberService.java
  src/main/java/com/fastcampus/jober/domain/spacewall/controller/SpaceWallCreationController.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/controller/SpaceWallHistoryController.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/service/SpaceWallHistoryService.java
  src/main/java/com/fastcampus/jober/domain/spacewallmember/controller/SpaceWallMemberController.java
  src/main/java/com/fastcampus/jober/domain/spacewallmember/service/SpaceWallMemberService.java
  src/main/java/com/fastcampus/jober/global/auth/session/MemberDetails.java
  src/main/java/com/fastcampus/jober/global/config/SecurityConfig.java
Labels: refactor

#93 공동작업자 삭제 쿼리 오류 수정
  src/main/java/com/fastcampus/jober/domain/spacewallmember/repository/SpaceWallMemberRepository.java
Labels: refactor

#94 공유스페이스 삭제 로직 수정
  src/main/java/com/fastcampus/jober/domain/spacewall/service/SpaceWallService.java
  src/main/java/com/fastcampus/jober/domain/spacewallpermission/repository/SpaceWallPermissionRepository.java
Labels: refactor

#98 공유스페이스 히스토리 수정 후 누락된 필드 추가 및 테이블 수정
  src/main/java/com/fastcampus/jober/domain/componenthistory/domain/ComponentHistory.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/dto/ComponentHistoryRequest.java
  src/main/java/com/fastcampus/jober/domain/componenthistory/dto/ComponentHistoryResponse.java
  src/main/java/com/fastcampus/jober/domain/member/controller/MemberController.java
  src/main/java/com/fastcampus/jober/domain/spacewallhistory/service/SpaceWallHistoryService.java
  src/main/java/com/fastcampus/jober/domain/spacewallmember/service/SpaceWallMemberService.java
  src/main/resources/db/table-mysql.sql
Labels: refactor

#104 /spaces/history uri 권한 오류 수정
  src/main/java/com/fastcampus/jober/global/security/manager/CustomAuthorizationManager.java
Labels: bug

#107 공유스페이스 생성 API 권한 체크 오류 수정
  src/main/java/com/fastcampus/jober/global/config/SecurityConfig.java
Labels: bug

#109 권한 체크 메서드 분리
  src/main/java/com/fastcampus/jober/global/config/SecurityConfig.java
  src/main/java/com/fastcampus/jober/global/security/filter/MyRequestFilter.java
  src/main/java/com/fastcampus/jober/global/security/manager/CustomAuthorizationManager.java
  src/main/java/com/fastcampus/jober/global/utils/RequestWrapper.java
Labels: refactor

#108 table.sql 수정 space_wall_permission.space_wall_member_id
  src/main/java/com/fastcampus/jober/domain/spacewallmember/service/SpaceWallMemberService.java
  src/main/resources/db/table-mysql.sql
Labels: refactor

#111 공유스페이스 생성 API 권한 처리 오류 수정
  src/main/java/com/fastcampus/jober/global/security/manager/CustomAuthorizationManager.java
Labels: bug

#116 공유스페이스 편집 완료 시, 템플릿 사용 이력 저장하는 기능 추가
  src/main/java/com/fastcampus/jober/domain/spacewalltemp/controller/SpaceWallTempController.java
  src/main/java/com/fastcampus/jober/domain/spacewalltemp/service/SpaceWallTempService.java
  src/main/java/com/fastcampus/jober/domain/template/service/TemplateUsedHistoryService.java
Labels: enhancement

#125 querydsl 셋팅
  build.gradle
  settings.gradle
Labels: enhancement

#127 querydsl 빌드 오류 수정
  build.gradle
Labels: bug

#129 fix : A5,6,7 requset, response 불필요 요소 삭제
  src/main/java/com/fastcampus/jober/domain/space/spacewall/spacewalltemp/dto/SpaceWallTempRequest.java
  src/main/java/com/fastcampus/jober/domain/space/spacewall/spacewalltemp/dto/SpaceWallTempResponse.java
  src/main/java/com/fastcampus/jober/domain/space/spacewall/spacewalltemp/repository/SpaceWallTempRepository.java
  src/main/java/com/fastcampus/jober/domain/space/spacewall/spacewalltemp/service/SpaceWallTempService.java
Labels: refactor

#130 템플릿 조회 시, 찜 여부 항목 추가
  src/main/java/com/fastcampus/jober/domain/template/service/TemplateService.java
Labels: enhancement
